---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    holland:
      password: "randompass"
    stack_commons:
      stackname: "pythonstack"
    pythonstack:
      demo:
        enabled: true
      webserver_deployment:
        enabled: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.6
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[wrapper]
    attributes:
      pythonstack:
        webserver: "apache"

  - name: default-nginx
    run_list:
      - recipe[wrapper]
    attributes:
      pythonstack:
        webserver: "nginx"
