---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    holland:
      password: "randompass"

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
    - recipe[build-essential::default]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    - recipe[build-essential::default]
  - name: centos-6.5
    run_list:
    - recipe[yum]
    - recipe[build-essential::default]

suites:
  - name: default
    run_list:
      - recipe[pythonstack::mysql_base]
      - recipe[pythonstack::postgresql_base]
      - recipe[pythonstack::mongodb_standalone]
      - recipe[pythonstack::memcache]
      - recipe[pythonstack::varnish]
      - recipe[pythonstack::rabbitmq]
      - recipe[pythonstack::redis_single]
      - recipe[pythonstack::application_python]
    attributes:
      pythonstack:
        demo:
          enabled: true

  - name: aio-nginx
    run_list:
      - recipe[pythonstack::mysql_base]
      - recipe[pythonstack::postgresql_base]
      - recipe[pythonstack::mongodb_standalone]
      - recipe[pythonstack::memcache]
      - recipe[pythonstack::varnish]
      - recipe[pythonstack::rabbitmq]
      - recipe[pythonstack::redis_single]
      - recipe[pythonstack::application_python]
    attributes:
      pythonstack:
        webserver: "nginx"
        demo:
          enabled: true

  - name: runlist
    run_list:
      - recipe[pythonstack::mysql_base]
      - recipe[pythonstack::postgresql_base]
      - recipe[pythonstack::mongodb_standalone]
      - recipe[pythonstack::memcache]
      - recipe[pythonstack::varnish]
      - recipe[pythonstack::rabbitmq]
      - recipe[pythonstack::redis_single]
      - recipe[pythonstack::application_python]
      - recipe[wrapper::demo]
    attributes:
      pythonstack:
        demo:
          enabled: true

  - name: wrapper
    run_list:
      - recipe[wrapper]

  - name: application-python-apache
    run_list:
      - recipe[pythonstack::application_python]
    attributes:
      pythonstack:
        demo:
          enabled: true

  - name: application-python-nginx
    run_list:
      - recipe[pythonstack::application_python]
    attributes:
      pythonstack:
        webserver: "nginx"
        demo:
          enabled: true

  - name: mysql
    run_list:
      - recipe[pythonstack::mysql_base]
    attributes:
      pythonstack:
        demo:
          enabled: true

  - name: postgresql
    run_list:
      - recipe[pythonstack::postgresql_base]
    attributes:
      pythonstack:
        demo:
          enabled: true
